export const AuthResult = {
	a: "LoginStatus",
	b: "UserSystem",
	c: "ChangePasswordDaysLeft",
	d: "UserEulas",
	e: "UserRoles",
	f: "LastLoginTime",
	g: "UserName",
	h: "ServerTime",
	i: "ServerInstanceName",
	j: "Servers",
	k: "CaptchaID",
	l: "Token",
	m: "AccountReports",
	n: "LastIP",
	o: "LastChangedPwd",
	p: "ShouldPerformDataCleansing",
	q: "SsoToken",
	t: "popMailDeliveryAgreement",
};

export const StructAccountTransaction = {
	a: "Account",
	b: "Date",
	c: "Bno_Number",
	d: "Ref",
	e: "Sug_Bno",
	f: "Bno_Name",
	i: "Nv",
	j: "Action",
	k: "Balance",
	l: "Comission",
	m: "Price",
	n: "NetCredit",
	o: "NetDebit",
	p: "Branch",
};

export const RMType = {
	a: "Sug",
	b: "ID",
	c: "BNO",
	d: "SUG_RC",
	e: "Tik",
	f: "Branch",
	g: "ID_NAME",
	h: "BS_BNO",
	i: "SYMBOL_NAM",
	j: "BNO_NAME",
	k: "SUG_ID",
	l: "SUG_BNO",
	m: "LAST_OP",
	n: "LAST_DT",
	o: "STRT_DT",
	p: "END_DT",
	q: "AV_TERM",
	r: "MDR",
	s: "MANPIK",
	t: "MNG_REP",
	u: "DERIV_COD",
	v: "SORT",
	w: "SH",
	x: "SUG_PR",
	y: "PRC",
	z: "PRC_CHNG",
	ba: "SUG_CUR",
	bb: "PR_MATACH",
	bc: "HON_RASHUM",
	bd: "NV",
	be: "COST",
	bf: "VL",
	bg: "EXT_MARGIN",
	bh: "REQ_MARGIN",
	bi: "SUM1",
	bj: "SUM2",
	bk: "ID_PCNT",
	bl: "TK_PCNT",
	bm: "LVL1",
	bn: "LVL2",
	bo: "LVL3",
	bp: "LVL4",
	bq: "LVL5",
	br: "LVL6",
	bs: "MANG_COD",
	bt: "BANK",
	bu: "BNK_BRANCH",
	bv: "ID_BANK",
	bw: "MDL",
	bx: "BLC",
	by: "BLC_NEG",
	bz: "BGT",
	ca: "SIVUG",
	cb: "INTRST_COD",
	cc: "PAY_MNG",
	cd: "FIL",
	ce: "IsNewStruct",
	cf: "BnoType",
	cg: "SugBno",
};

export const RMTotalType = {
	a: "UpdateDate",
	b: "AccountValue",
	c: "Exist_Marg",
	d: "Req_Marg",
	e: "Income",
	f: "Credit",
	g: "Cash",
	h: "ImmediateWithdraw",
	i: "UnsettledCashBuy",
	j: "UnsettledCashSell",
};

export const SecuritiesData = {
	a: "Totals",
	b: "AssetMargins",
};

export const SecuritiesTotalType = {
	a: "CashMorning",
	b: "NezilimMorning",
	c: "Premia",
	d: "CashCurrent",
	e: "NezilimCurrent",
	f: "ReqMargin",
	g: "ReqMarginMaof",
	h: "ReqMarginHul",
	i: "ReqMarginStocks",
	j: "ReqMarginMatach",
	k: "MarginCurrent",
	l: "RezefChange",
	m: "Misgeret",
	n: "Harshaa",
	o: "AccountValueMorning",
	p: "Tax",
	q: "AddMofLong",
	r: "AddMofShort",
	s: "AddRzfLong",
	t: "AddRzfShort",
};

export const ChartPoint = {
	a: "key",
	b: "max",
	c: "min",
	d: "open",
	e: "close",
	f: "time",
	g: "volume",
	h: "ParsedTime",
	i: "pcnt",
};
